version: '3.8'
services:


  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    # ports:
    #  - "5432:5432"

  backend:
    image: vakafm/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: vakafm/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    
volumes:
  static_value:
  media_value:
  postgres_data:
  result_build: